branch-defaults:
  main:
    environment: nodejs-env
    group_suffix: null
global:
  application_name: tbt-companion-backend
  branch: null
  default_ec2_keyname: tbt-comp-back-ssh
  default_platform: Node.js 22
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application

